"""GitAgent public API."""

from gitagent.application import GitAgentService, RuntimeConfig
from gitagent.capability import (
    AccessLevel,
    Capability,
    CapabilityError,
    CapabilityErrorType,
    CapabilityKind,
    CapabilityLayer,
    CapabilityResult,
    CapabilityStatus,
    InvocationContext,
    PermissionPolicy,
)
from gitagent.domain.models import (
    ApprovalIntent,
    CandidatePatch,
    ChangeRequest,
    CodeExplanationResult,
    CodePlanResult,
    CodeReviewResult,
    DomainAction,
    IssueAgentResult,
    IssueOperation,
    IssueSummary,
    MainDecision,
    MutationRejectedResult,
    PullRequestAgentResult,
    PullRequestOperation,
    PullRequestSummary,
    Replacement,
    Route,
    SessionEvent,
    WorkflowTurnDecision,
)
from gitagent.harness import AgentHarness
from gitagent.harness.constraints import ApprovalRequest, ApprovalStore
from gitagent.infra.github import GitHubClient, InMemoryGitHubClient
from gitagent.infra.observability import (
    TraceBus,
    TraceCategory,
    TraceEvent,
    TraceStatus,
)
from gitagent.model import (
    ChatResponse,
    LiteLLMChatClient,
    LLMReasoner,
    OpenAIChatClient,
)

__version__ = "0.1.0"

__all__ = [
    "AccessLevel",
    "AgentHarness",
    "ApprovalIntent",
    "ApprovalRequest",
    "ApprovalStore",
    "CandidatePatch",
    "Capability",
    "CapabilityError",
    "CapabilityErrorType",
    "CapabilityKind",
    "CapabilityLayer",
    "CapabilityResult",
    "CapabilityStatus",
    "ChangeRequest",
    "ChatResponse",
    "CodeExplanationResult",
    "CodePlanResult",
    "CodeReviewResult",
    "DomainAction",
    "GitAgentService",
    "GitHubClient",
    "InMemoryGitHubClient",
    "InvocationContext",
    "IssueAgentResult",
    "IssueOperation",
    "IssueSummary",
    "LLMReasoner",
    "LiteLLMChatClient",
    "MainDecision",
    "MutationRejectedResult",
    "OpenAIChatClient",
    "PermissionPolicy",
    "PullRequestAgentResult",
    "PullRequestOperation",
    "PullRequestSummary",
    "Replacement",
    "Route",
    "RuntimeConfig",
    "SessionEvent",
    "TraceBus",
    "TraceCategory",
    "TraceEvent",
    "TraceStatus",
    "WorkflowTurnDecision",
    "__version__",
]
